r"""Evaluate the current parser against the private flight shape corpus.

This is a local-only scoreboard for parser redesign work. It reads the
redacted shape corpus generated by ``flight_shape_corpus.py`` plus the copied
catalog export, runs the current parser, and reports recall/timing by message
shape without mutating application state.

Usage:
    cd backend
    poetry run python scripts\evaluate_shape_corpus.py --reference-export C:\Projects\Trotter\trotter-parser-test-data-20260526-134009\cataloged_flights_export.json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.services.parser import ParsedFlight, parse_email  # noqa: E402
from app.services.parser_preprocess import prepare_parser_text  # noqa: E402


SCRIPT_DIR = Path(__file__).resolve().parent
CORPUS_DIR = SCRIPT_DIR / ".flight_shape_corpus"
DEFAULT_MANIFEST = CORPUS_DIR / "manifest.json"
DEFAULT_REPORT = CORPUS_DIR / "evaluation_report.md"
DEFAULT_JSON = CORPUS_DIR / "evaluation_results.json"
DEFAULT_EXTRA_REVIEW_NOTES = CORPUS_DIR / "extra_review_notes.json"
INVALID_REFERENCE_PNRS = {"EMAIL", "LETTER", "POLICY"}
ACTIONABLE_MISSING_REASONS = {"visible_parser_miss", "no_visible_evidence"}
AUTO_RESOLVED_EXTRA_CLASSIFICATIONS = {
    "check_in_email_update_evidence",
    "duplicate_or_update_evidence",
    "pnr_alias_same_trip",
}
MANUAL_MISSING_REASON_OVERRIDES = {
    # Manually reviewed on 2026-05-27. These messages are useful evidence,
    # but the reference catalog intentionally contains broader same-PNR trip
    # context than each individual email displays.
    "166cbeab130f8b1c": "checkin_single_leg_expected",
    "166dba04e9a4a002": "checkin_single_leg_expected",
    "16af99c97bf98a19": "checkin_single_leg_expected",
    "16e280b4f39ef4bc": "catalog_summary_route",
    "1764ff26482f1719": "checkin_single_leg_expected",
    "176e696f53faff7c": "checkin_single_leg_expected",
    "176e6a07de8f9764": "checkin_single_leg_expected",
    "1826021c91a959ae": "superseded_by_change",
    "18288cdc387d8755": "change_notice_replaces_prior",
    "1828f323585f4358": "partial_reminder_evidence",
    "183749e03b4fd503": "checkin_single_leg_expected",
    "1854ee1098832ea1": "reminder_single_leg_expected",
    "18c00ff510dc2a6b": "partial_reminder_evidence",
    "190463c3a3bbefd8": "checkin_single_leg_expected",
    "19084609567cb9a1": "partial_confirmation_expected",
    "19429aece2d1324e": "canceled_booking_sibling",
    "196717b1434a5404": "upgrade_duplicate_evidence",
    "1970aacf95183f3c": "change_notice_replaces_canceled_booking",
}


@dataclass(frozen=True)
class ExpectedSegment:
    pnr: str
    airline: str | None
    flight_number: str | None
    dep_airport: str
    arr_airport: str
    dep_time: str
    arr_time: str
    trip_id: int | None
    trip_title: str | None
    source_message_id: str | None


@dataclass(frozen=True)
class ParsedSegment:
    pnr: str | None
    airline: str | None
    flight_number: str | None
    dep_airport: str
    arr_airport: str
    dep_time: str | None
    arr_time: str | None
    source: str | None


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--reference-export", type=Path, required=True)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--json-output", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--report-output", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--extra-review-notes", type=Path, default=DEFAULT_EXTRA_REVIEW_NOTES)
    parser.add_argument("--max-seconds", type=float, default=None)
    parser.add_argument("--max-message-seconds", type=float, default=None)
    parser.add_argument("--min-match-rate", type=float, default=None)
    parser.add_argument("--max-missing", type=int, default=None)
    parser.add_argument("--max-extras", type=int, default=None)
    parser.add_argument("--max-errors", type=int, default=0)
    args = parser.parse_args()

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    reference = load_reference(args.reference_export)
    extra_review_notes = load_extra_review_notes(args.extra_review_notes)
    records = manifest.get("records") or []
    if args.limit:
        records = records[: args.limit]

    started = time.perf_counter()
    results = []
    for index, record in enumerate(records, 1):
        result = evaluate_record(record, reference, extra_review_notes)
        results.append(result)
        print(
            f"{index:>4}/{len(records)} {record.get('shape','-'):<22} "
            f"{result['elapsed_seconds']:>6.2f}s "
            f"expected={result['expected_count']} parsed={result['parsed_count']} "
            f"matched={result['matched_count']} {record.get('message_id')}",
            flush=True,
        )

    payload = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "manifest": str(args.manifest),
        "reference_export": str(args.reference_export),
        "extra_review_notes": str(args.extra_review_notes) if args.extra_review_notes.exists() else None,
        "elapsed_seconds": round(time.perf_counter() - started, 3),
        "summary": summarize_results(results),
        "results": results,
    }
    args.json_output.parent.mkdir(parents=True, exist_ok=True)
    args.json_output.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    args.report_output.write_text(render_report(payload), encoding="utf-8")
    print(render_report(payload), end="")
    print(f"JSON:   {args.json_output}")
    print(f"Report: {args.report_output}")
    threshold_failures = check_thresholds(payload["summary"], args)
    if threshold_failures:
        print("Threshold failures:", file=sys.stderr)
        for failure in threshold_failures:
            print(f"- {failure}", file=sys.stderr)
        raise SystemExit(1)


def load_reference(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    messages_by_ts = {
        _normal_timestamp(row.get("internal_ts")): row
        for row in payload.get("messages") or []
        if row.get("provider_msg_id") and row.get("internal_ts")
    }
    expected_by_message: dict[str, list[ExpectedSegment]] = defaultdict(list)
    expected_by_pnr: dict[str, list[ExpectedSegment]] = defaultdict(list)
    invalid_pnrs = Counter()
    for segment in payload.get("segments") or []:
        raw_pnr = _normal_code(segment.get("pnr"))
        if not raw_pnr or raw_pnr in INVALID_REFERENCE_PNRS:
            if raw_pnr:
                invalid_pnrs[raw_pnr] += 1
            continue
        source_message_id = None
        meta = segment.get("meta_json") if isinstance(segment.get("meta_json"), dict) else {}
        source_ts = _normal_timestamp(meta.get("source_received_at"))
        if source_ts in messages_by_ts:
            source_message_id = messages_by_ts[source_ts]["provider_msg_id"]
        expected = ExpectedSegment(
            pnr=raw_pnr,
            airline=_normal_code(segment.get("airline")),
            flight_number=_normal_flight_number(segment.get("flight_number")),
            dep_airport=_normal_code(segment.get("dep_airport")) or "",
            arr_airport=_normal_code(segment.get("arr_airport")) or "",
            dep_time=str(segment.get("dep_time") or ""),
            arr_time=str(segment.get("arr_time") or ""),
            trip_id=segment.get("trip_id"),
            trip_title=segment.get("trip_title"),
            source_message_id=source_message_id,
        )
        expected_by_pnr[expected.pnr].append(expected)
        if source_message_id:
            expected_by_message[source_message_id].append(expected)
    return {
        "expected_by_message": expected_by_message,
        "expected_by_pnr": expected_by_pnr,
        "invalid_pnrs": dict(invalid_pnrs),
    }


def load_extra_review_notes(path: Path) -> dict[tuple[str, str], dict[str, Any]]:
    if not path.exists():
        return {}
    payload = json.loads(path.read_text(encoding="utf-8"))
    notes = {}
    for item in payload if isinstance(payload, list) else []:
        message_id = str(item.get("messageId") or "")
        reason = str(item.get("reason") or "")
        if message_id and reason:
            notes[(message_id, reason)] = item
    return notes


def evaluate_record(
    record: dict[str, Any],
    reference: dict[str, Any],
    extra_review_notes: dict[tuple[str, str], dict[str, Any]] | None = None,
) -> dict[str, Any]:
    message_path = CORPUS_DIR / (record.get("message_path") or "")
    message = json.loads(message_path.read_text(encoding="utf-8"))
    expected = expected_segments_for_record(record, reference)
    evidence_text = message_evidence_text(message)

    started = time.perf_counter()
    error = None
    parsed_result = None
    try:
        diagnostics: dict[str, Any] = {}
        parsed_result = parse_email(
            html=message.get("html") or "",
            plain_text=message.get("plain_text") or "",
            attachments=[],
            user_name="",
            aliases=[],
            received_at=message.get("date") or None,
            subject=message.get("subject") or "",
            from_email=message.get("from") or "",
            diagnostics=diagnostics,
        )
        parsed = [parsed_to_segment(flight) for flight in parsed_result.flights]
    except Exception as exc:  # noqa: BLE001
        error = f"{type(exc).__name__}: {exc}"
        parsed = []
        diagnostics = {}
    elapsed = time.perf_counter() - started

    matches, missing, extras = match_segments(expected, parsed)
    missing_analysis = [
        classify_missing_segment(segment, record=record, evidence_text=evidence_text, parsed=parsed)
        for segment in missing
    ]
    actionable_missing = [
        item for item in missing_analysis
        if item.get("reason") in ACTIONABLE_MISSING_REASONS
    ]
    return {
        "message_id": record.get("message_id"),
        "shape": record.get("shape"),
        "sender_domain": record.get("sender_domain"),
        "subject": record.get("subject"),
        "pnrs": record.get("pnrs") or [],
        "expected_count": len(expected),
        "parsed_count": len(parsed),
        "matched_count": len(matches),
        "missing_count": len(missing),
        "actionable_missing_count": len(actionable_missing),
        "extra_count": len(extras),
        "elapsed_seconds": round(elapsed, 4),
        "parser_source": getattr(parsed_result, "source", None) if parsed_result else None,
        "parser_diagnostics": diagnostics,
        "error": error,
        "expected": [asdict(item) for item in expected],
        "parsed": [asdict(item) for item in parsed],
        "matches": matches,
        "missing": [asdict(item) for item in missing],
        "missing_analysis": missing_analysis,
        "extras": [asdict(item) for item in extras],
        "extra_analysis": [
            classify_extra_segment(
                item,
                record=record,
                expected=expected,
                reference=reference,
                review_notes=extra_review_notes or {},
            )
            for item in extras
        ],
    }


def expected_segments_for_record(record: dict[str, Any], reference: dict[str, Any]) -> list[ExpectedSegment]:
    by_message = reference["expected_by_message"]
    by_pnr = reference["expected_by_pnr"]
    message_id = record.get("message_id")
    if message_id in by_message:
        return sorted(by_message[message_id], key=expected_sort_key)
    expected: dict[tuple, ExpectedSegment] = {}
    for pnr in record.get("pnrs") or []:
        for segment in by_pnr.get(pnr, []):
            expected[expected_sort_key(segment)] = segment
    return [expected[key] for key in sorted(expected)]


def match_segments(
    expected: list[ExpectedSegment], parsed: list[ParsedSegment]
) -> tuple[list[dict[str, Any]], list[ExpectedSegment], list[ParsedSegment]]:
    unused = list(range(len(parsed)))
    matches = []
    missing = []
    for exp in expected:
        best_index = None
        best_score = -1
        best_reasons: list[str] = []
        for idx in unused:
            score, reasons = score_match(exp, parsed[idx])
            if score > best_score:
                best_score = score
                best_index = idx
                best_reasons = reasons
        if best_index is not None and best_score >= 7:
            parsed_item = parsed[best_index]
            matches.append(
                {
                    "score": best_score,
                    "reasons": best_reasons,
                    "expected": asdict(exp),
                    "parsed": asdict(parsed_item),
                }
            )
            unused.remove(best_index)
        else:
            missing.append(exp)
    return matches, missing, [parsed[idx] for idx in unused]


def score_match(expected: ExpectedSegment, parsed: ParsedSegment) -> tuple[int, list[str]]:
    score = 0
    reasons = []
    if expected.dep_airport == parsed.dep_airport and expected.arr_airport == parsed.arr_airport:
        score += 5
        reasons.append("route")
    if expected.flight_number and parsed.flight_number and expected.flight_number == parsed.flight_number:
        score += 3
        reasons.append("flight_number")
    if expected.pnr and parsed.pnr and expected.pnr == parsed.pnr:
        score += 2
        reasons.append("pnr")
    if expected_dep_date(expected) and parsed_dep_date(parsed) and expected_dep_date(expected) == parsed_dep_date(parsed):
        score += 2
        reasons.append("dep_date")
    if expected.airline and parsed.airline and expected.airline == parsed.airline:
        score += 1
        reasons.append("airline")
    return score, reasons


def parsed_to_segment(flight: ParsedFlight) -> ParsedSegment:
    return ParsedSegment(
        pnr=_normal_code(flight.pnr),
        airline=_normal_code(flight.airline),
        flight_number=_normal_flight_number(flight.flight_number),
        dep_airport=_normal_code(flight.dep_airport) or "",
        arr_airport=_normal_code(flight.arr_airport) or "",
        dep_time=flight.dep_time.isoformat() if flight.dep_time else None,
        arr_time=flight.arr_time.isoformat() if flight.arr_time else None,
        source=flight.source,
    )


def summarize_results(results: list[dict[str, Any]]) -> dict[str, Any]:
    expected_total = sum(row["expected_count"] for row in results)
    parsed_total = sum(row["parsed_count"] for row in results)
    matched_total = sum(row["matched_count"] for row in results)
    missing_total = sum(row["missing_count"] for row in results)
    actionable_missing_total = sum(row.get("actionable_missing_count", row["missing_count"]) for row in results)
    errors = [row for row in results if row.get("error")]
    by_shape = {}
    stage_totals: Counter[str] = Counter()
    slowest_stage_messages: dict[str, list[dict[str, Any]]] = defaultdict(list)
    forwarded = Counter()
    missing_reasons = Counter()
    extra_reasons = Counter()
    extra_review_classifications = Counter()
    parser_sources = Counter()
    pnr_aliases = Counter()
    for shape, rows in group_by(results, "shape").items():
        by_shape[shape] = {
            "messages": len(rows),
            "expected": sum(row["expected_count"] for row in rows),
            "parsed": sum(row["parsed_count"] for row in rows),
            "matched": sum(row["matched_count"] for row in rows),
            "missing": sum(row["missing_count"] for row in rows),
            "actionable_missing": sum(row.get("actionable_missing_count", row["missing_count"]) for row in rows),
            "seconds": round(sum(row["elapsed_seconds"] for row in rows), 3),
        }
    for row in results:
        parser_sources[str(row.get("parser_source") or "unknown")] += 1
        for item in row.get("missing_analysis") or []:
            missing_reasons[item.get("reason") or "unknown"] += 1
        for item in row.get("extra_analysis") or []:
            extra_reasons[item.get("reason") or "unknown"] += 1
            if item.get("review_classification"):
                extra_review_classifications[item["review_classification"]] += 1
        for match in row.get("matches") or []:
            expected_pnr = ((match.get("expected") or {}).get("pnr") or "").upper()
            parsed_pnr = ((match.get("parsed") or {}).get("pnr") or "").upper()
            if expected_pnr and parsed_pnr and expected_pnr != parsed_pnr:
                pnr_aliases[f"{parsed_pnr}->{expected_pnr}"] += 1
        diagnostics = row.get("parser_diagnostics") or {}
        if diagnostics.get("is_forwarded"):
            forwarded["messages"] += 1
            forwarded["matched"] += row["matched_count"]
            forwarded["expected"] += row["expected_count"]
            forwarded["seconds"] += row["elapsed_seconds"]
        for key, value in diagnostics.items():
            if key.endswith("_seconds") and isinstance(value, (int, float)):
                stage_totals[key] += float(value)
                slowest_stage_messages[key].append(
                    {
                        "message_id": row["message_id"],
                        "shape": row["shape"],
                        "seconds": round(float(value), 4),
                        "subject": row["subject"],
                    }
                )
    slowest = sorted(results, key=lambda row: row["elapsed_seconds"], reverse=True)[:15]
    return {
        "messages": len(results),
        "expected_segments": expected_total,
        "parsed_segments": parsed_total,
        "matched_segments": matched_total,
        "missing_segments": missing_total,
        "evidence_gap_segments": missing_total,
        "actionable_missing_segments": actionable_missing_total,
        "extra_segments": sum(row["extra_count"] for row in results),
        "match_rate": round(matched_total / expected_total, 4) if expected_total else 0,
        "error_count": len(errors),
        "seconds": round(sum(row["elapsed_seconds"] for row in results), 3),
        "by_shape": by_shape,
        "stage_seconds": {key: round(value, 3) for key, value in sorted(stage_totals.items())},
        "missing_reasons": dict(sorted(missing_reasons.items())),
        "evidence_gap_reasons": dict(sorted(missing_reasons.items())),
        "extra_reasons": dict(sorted(extra_reasons.items())),
        "extra_review_classifications": dict(sorted(extra_review_classifications.items())),
        "pnr_aliases": dict(sorted(pnr_aliases.items())),
        "parser_sources": dict(sorted(parser_sources.items())),
        "slowest_by_stage": {
            key: sorted(rows, key=lambda item: item["seconds"], reverse=True)[:5]
            for key, rows in sorted(slowest_stage_messages.items())
        },
        "forwarded": dict(forwarded),
        "slowest": [
            {
                "message_id": row["message_id"],
                "shape": row["shape"],
                "sender_domain": row["sender_domain"],
                "seconds": row["elapsed_seconds"],
                "expected": row["expected_count"],
                "matched": row["matched_count"],
                "subject": row["subject"],
            }
            for row in slowest
        ],
    }


def render_report(payload: dict[str, Any]) -> str:
    summary = payload["summary"]
    lines = [
        "# Shape Corpus Evaluation",
        "",
        f"- Messages evaluated: {summary['messages']}",
        f"- Expected segments: {summary['expected_segments']}",
        f"- Parsed segments: {summary['parsed_segments']}",
        f"- Matched segments: {summary['matched_segments']}",
        f"- Partial/context evidence gaps: {summary.get('evidence_gap_segments', summary['missing_segments'])}",
        f"- Actionable parser misses: {summary.get('actionable_missing_segments', summary['missing_segments'])}",
        f"- Extra parsed candidates: {summary['extra_segments']}",
        f"- Match rate: {summary['match_rate']:.1%}",
        f"- Parser errors: {summary['error_count']}",
        f"- Total parser time: {summary['seconds']:.2f}s",
        "",
        "## By Shape",
        "",
        "| Shape | Messages | Expected | Parsed | Matched | Evidence Gaps | Parser Misses | Seconds |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for shape, stats in sorted(summary["by_shape"].items(), key=lambda item: item[1]["missing"], reverse=True):
        lines.append(
            f"| {shape} | {stats['messages']} | {stats['expected']} | {stats['parsed']} | "
            f"{stats['matched']} | {stats['missing']} | {stats.get('actionable_missing', stats['missing'])} | {stats['seconds']:.2f} |"
        )
    lines.extend(["", "## Slowest Messages", ""])
    for row in summary["slowest"]:
        lines.append(
            f"- {row['seconds']:.2f}s `{row['message_id']}` `{row['shape']}` "
            f"`{row['sender_domain']}` matched={row['matched']}/{row['expected']} "
            f"{_safe_inline(row['subject'])}"
        )
    if summary.get("stage_seconds"):
        lines.extend(["", "## Parser Stage Timings", ""])
        for stage, seconds in summary["stage_seconds"].items():
            lines.append(f"- `{stage}`: {seconds:.2f}s")
    if summary.get("parser_sources"):
        lines.extend(["", "## Parser Sources", ""])
        for source, count in summary["parser_sources"].items():
            lines.append(f"- `{source}`: {count}")
    if summary.get("evidence_gap_reasons"):
        lines.extend(["", "## Evidence Gap Reasons", ""])
        for reason, count in summary["evidence_gap_reasons"].items():
            lines.append(f"- `{reason}`: {count}")
    if summary.get("extra_reasons"):
        lines.extend(["", "## Extra Candidate Reasons", ""])
        for reason, count in summary["extra_reasons"].items():
            lines.append(f"- `{reason}`: {count}")
    if summary.get("extra_review_classifications"):
        lines.extend(["", "## Extra Review Classifications", ""])
        for classification, count in summary["extra_review_classifications"].items():
            lines.append(f"- `{classification}`: {count}")
    if summary.get("pnr_aliases"):
        lines.extend(["", "## PNR Alias Matches", ""])
        for alias, count in summary["pnr_aliases"].items():
            lines.append(f"- `{alias}`: {count}")
    if summary.get("slowest_by_stage"):
        lines.extend(["", "## Slowest Stage Messages", ""])
        for stage, rows in summary["slowest_by_stage"].items():
            lines.append(f"### {stage}")
            for row in rows:
                lines.append(
                    f"- {row['seconds']:.2f}s `{row['message_id']}` `{row['shape']}` "
                    f"{_safe_inline(row['subject'])}"
                )
    lines.extend(["", "## Actionable Parser Misses", ""])
    misses = [row for row in payload["results"] if row.get("actionable_missing_count", row["missing_count"])]
    misses.sort(key=lambda row: (row["missing_count"], row["expected_count"], row["elapsed_seconds"]), reverse=True)
    for row in misses[:30]:
        missing_routes = ", ".join(
            f"{item['flight_number'] or '-'} {item['dep_airport']}->{item['arr_airport']} {item['pnr']}"
            for item in row["missing"][:4]
        )
        reasons = Counter(item.get("reason") or "unknown" for item in row.get("missing_analysis") or [])
        reason_text = ", ".join(f"{key}={value}" for key, value in sorted(reasons.items()))
        lines.append(
            f"- `{row['message_id']}` `{row['shape']}` `{row['sender_domain']}` "
            f"matched={row['matched_count']}/{row['expected_count']} "
            f"reasons: {reason_text or 'unknown'} missing: {missing_routes}"
        )
    if not misses:
        lines.append("- None")
    lines.extend(["", "## Extra Candidate Samples", ""])
    extras = [
        (row, item)
        for row in payload["results"]
        for item in row.get("extra_analysis") or []
    ]
    reason_order = {
        "possible_overparse_or_catalog_gap": 0,
        "uncataloged_candidate": 1,
        "same_pnr_update_or_duplicate_evidence": 2,
        "cataloged_under_other_pnr_or_alias": 3,
        "same_email_unmatched_candidate": 4,
    }
    extras.sort(key=lambda pair: (reason_order.get(pair[1].get("reason"), 9), pair[0]["message_id"]))
    for row, item in extras[:30]:
        segment = item.get("segment") or {}
        lines.append(
            f"- `{item.get('reason')}` `{row['message_id']}` `{row['shape']}` "
            f"{segment.get('flight_number') or '-'} {segment.get('dep_airport')}->{segment.get('arr_airport')} "
            f"{segment.get('pnr') or '-'} source={segment.get('source') or '-'} "
            f"{_safe_inline(row.get('subject'))}"
        )
    return "\n".join(lines) + "\n"


def message_evidence_text(message: dict[str, Any]) -> str:
    bundle = prepare_parser_text(
        html=message.get("html") or "",
        plain_text=message.get("plain_text") or "",
        subject=message.get("subject") or "",
        from_email=message.get("from") or "",
    )
    return "\n".join(
        part
        for part in [
            message.get("subject") or "",
            bundle.evidence_text,
            bundle.table_text,
            bundle.clean_text,
        ]
        if part
    ).upper()


def classify_missing_segment(
    segment: ExpectedSegment,
    *,
    record: dict[str, Any],
    evidence_text: str,
    parsed: list[ParsedSegment] | None = None,
) -> dict[str, Any]:
    parsed = parsed or []
    override_reason = MANUAL_MISSING_REASON_OVERRIDES.get(str(record.get("message_id") or ""))
    visible_signals = visible_expected_signals(segment, evidence_text)
    manual_reviewed = override_reason is not None
    if override_reason:
        reason = override_reason
    elif catalog_summary_route_covered(segment, parsed):
        reason = "catalog_summary_route"
    elif "flight_number" in visible_signals and "route" in visible_signals and "date" in visible_signals:
        reason = "visible_parser_miss"
    elif "route" in visible_signals and "time" in visible_signals and "date" in visible_signals:
        reason = "visible_parser_miss"
    elif record.get("message_id") and segment.source_message_id and segment.source_message_id != record.get("message_id"):
        if is_checkin_or_reminder_record(record, evidence_text):
            reason = "checkin_single_leg_expected"
        elif is_change_notice_record(record, evidence_text):
            reason = "change_notice_sibling"
        else:
            reason = "same_pnr_other_email"
    elif is_sparse_reminder_record(record, evidence_text) and not {"flight_number", "route", "date"} <= set(visible_signals):
        reason = "partial_reminder_evidence"
    elif segment.pnr in set(record.get("pnrs") or []):
        reason = "pnr_sibling_or_catalog_scope"
    else:
        reason = "no_visible_evidence"
    return {
        "segment": asdict(segment),
        "reason": reason,
        "manual_reviewed": manual_reviewed,
        "visible_signals": visible_signals,
    }


def classify_extra_segment(
    segment: ParsedSegment,
    *,
    record: dict[str, Any],
    expected: list[ExpectedSegment],
    reference: dict[str, Any],
    review_notes: dict[tuple[str, str], dict[str, Any]] | None = None,
) -> dict[str, Any]:
    expected_for_pnr = reference["expected_by_pnr"].get(segment.pnr, []) if segment.pnr else []
    all_expected = all_reference_segments(reference)
    if parsed_matches_any_expected(segment, expected):
        reason = "same_email_unmatched_candidate"
    elif parsed_matches_any_expected(segment, expected_for_pnr):
        reason = "same_pnr_update_or_duplicate_evidence"
    elif parsed_matches_any_expected(segment, all_expected, ignore_pnr=True):
        reason = "cataloged_under_other_pnr_or_alias"
    elif not expected:
        reason = "uncataloged_candidate"
    else:
        reason = "possible_overparse_or_catalog_gap"
    note = (review_notes or {}).get((str(record.get("message_id") or ""), reason))
    review_classification = note.get("classification") if note else None
    review_note = note.get("note") if note else None
    review_source = "manual" if note else None
    if not review_classification and is_subject_checkin(record):
        review_classification = "check_in_email_update_evidence"
        review_source = "subject_checkin_rule"
    return {
        "segment": asdict(segment),
        "reason": reason,
        "message_id": record.get("message_id"),
        "review_classification": review_classification,
        "review_note": review_note,
        "review_source": review_source,
        "review_resolved": bool(
            review_classification
            and review_classification != "needs_more_investigation"
        ),
    }


def is_subject_checkin(record: dict[str, Any]) -> bool:
    subject = str(record.get("subject") or "").lower()
    return bool(re.search(r"\bcheck[\s-]?in\b", subject))


def all_reference_segments(reference: dict[str, Any]) -> list[ExpectedSegment]:
    deduped: dict[tuple, ExpectedSegment] = {}
    for rows in reference["expected_by_pnr"].values():
        for segment in rows:
            deduped[expected_sort_key(segment)] = segment
    return list(deduped.values())


def parsed_matches_any_expected(
    parsed: ParsedSegment,
    expected_segments: list[ExpectedSegment],
    *,
    ignore_pnr: bool = False,
) -> bool:
    for expected in expected_segments:
        if parsed.dep_airport != expected.dep_airport or parsed.arr_airport != expected.arr_airport:
            continue
        if parsed_dep_date(parsed) != expected_dep_date(expected):
            continue
        if not ignore_pnr and parsed.pnr and expected.pnr and parsed.pnr != expected.pnr:
            continue
        if parsed.flight_number and expected.flight_number and parsed.flight_number != expected.flight_number:
            continue
        return True
    return False


def catalog_summary_route_covered(segment: ExpectedSegment, parsed: list[ParsedSegment]) -> bool:
    if segment.flight_number:
        return False
    same_day = [
        item for item in parsed
        if item.pnr == segment.pnr and parsed_dep_date(item) == expected_dep_date(segment)
    ]
    if len(same_day) < 2:
        return False
    adjacency: dict[str, set[str]] = defaultdict(set)
    for item in same_day:
        adjacency[item.dep_airport].add(item.arr_airport)
    stack = [segment.dep_airport]
    seen = set()
    while stack:
        airport = stack.pop()
        if airport == segment.arr_airport:
            return True
        if airport in seen:
            continue
        seen.add(airport)
        stack.extend(adjacency.get(airport, set()) - seen)
    return False


def is_checkin_or_reminder_record(record: dict[str, Any], evidence_text: str) -> bool:
    shape = (record.get("shape") or "").lower()
    subject = (record.get("subject") or "").lower()
    return (
        "checkin" in shape
        or "reminder" in shape
        or "check in" in subject
        or "check-in" in subject
    )


def is_change_notice_record(record: dict[str, Any], evidence_text: str) -> bool:
    shape = (record.get("shape") or "").lower()
    subject = (record.get("subject") or "").lower()
    lower = evidence_text.lower()
    return "change" in shape or "changed" in subject or "change is confirmed" in lower[:1500]


def is_sparse_reminder_record(record: dict[str, Any], evidence_text: str) -> bool:
    subject = (record.get("subject") or "").lower()
    lower = evidence_text.lower()
    return (
        "what you'll need" in subject
        or "what you will need" in subject
        or "get prepared to fly" in subject
        or "when to arrive" in lower[:1500]
    )


def visible_expected_signals(segment: ExpectedSegment, evidence_text: str) -> list[str]:
    evidence_text = evidence_text.upper()
    signals: list[str] = []
    normalized_flights = normalize_flight_text(evidence_text)
    if segment.flight_number and (
        segment.flight_number in normalized_flights
        or segment.flight_number[2:] in visible_flight_number_tokens(segment, normalized_flights)
    ):
        signals.append("flight_number")
    route_patterns = [
        rf"\b{re.escape(segment.dep_airport)}\s+(?:TO|->|-)\s+{re.escape(segment.arr_airport)}\b",
        rf"\b(?:DEPARTS?|FROM)\b[\s\S]{{0,80}}\b{re.escape(segment.dep_airport)}\b[\s\S]{{0,160}}\b(?:ARRIVES?|TO)\b[\s\S]{{0,80}}\b{re.escape(segment.arr_airport)}\b",
    ]
    if any(re.search(pattern, evidence_text) for pattern in route_patterns):
        signals.append("route")
    if segment.pnr and segment.pnr in evidence_text:
        signals.append("pnr")
    if any(hint and hint in evidence_text for hint in date_hints(segment.dep_time)):
        signals.append("date")
    if any(hint and hint in evidence_text for hint in time_hints(segment.dep_time)):
        signals.append("time")
    return signals


def normalize_flight_text(value: str) -> str:
    return re.sub(r"\b([A-Z0-9]{2})\s+(\d{1,4}[A-Z]?)\b", r"\1\2", value.upper())


def visible_flight_number_tokens(segment: ExpectedSegment, evidence_text: str) -> set[str]:
    if not segment.flight_number:
        return set()
    number = segment.flight_number[2:]
    tokens = set()
    if re.search(rf"\b(?:FLIGHT\s*)?#\s*{re.escape(number)}\b", evidence_text):
        tokens.add(number)
    return tokens


def date_hints(value: str) -> list[str]:
    try:
        dt = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except ValueError:
        return []
    month_name = dt.strftime("%B")
    month_abbrev = dt.strftime("%b")
    return [
        dt.strftime("%Y-%m-%d").upper(),
        dt.strftime("%m/%d/%Y").upper(),
        f"{dt.month}/{dt.day}/{dt.year}".upper(),
        f"{month_name} {dt.day}".upper(),
        f"{month_abbrev} {dt.day}".upper(),
        dt.strftime("%d %b %Y").upper(),
    ]


def time_hints(value: str) -> list[str]:
    try:
        dt = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except ValueError:
        return []
    return [
        dt.strftime("%H:%M").upper(),
        dt.strftime("%I:%M %p").lstrip("0").upper(),
    ]


def check_thresholds(summary: dict[str, Any], args: argparse.Namespace) -> list[str]:
    failures = []
    if args.max_errors is not None and summary["error_count"] > args.max_errors:
        failures.append(f"errors {summary['error_count']} > {args.max_errors}")
    if args.max_seconds is not None and summary["seconds"] > args.max_seconds:
        failures.append(f"total seconds {summary['seconds']:.2f} > {args.max_seconds:.2f}")
    if args.max_message_seconds is not None:
        slowest = max((row["seconds"] for row in summary.get("slowest") or []), default=0)
        if slowest > args.max_message_seconds:
            failures.append(f"slowest message {slowest:.2f}s > {args.max_message_seconds:.2f}s")
    if args.min_match_rate is not None and summary["match_rate"] < args.min_match_rate:
        failures.append(f"match rate {summary['match_rate']:.1%} < {args.min_match_rate:.1%}")
    if args.max_missing is not None and summary["missing_segments"] > args.max_missing:
        actionable_missing = summary.get("actionable_missing_segments", summary["missing_segments"])
        if actionable_missing > args.max_missing:
            failures.append(f"actionable missing {actionable_missing} > {args.max_missing}")
    if args.max_extras is not None and summary["extra_segments"] > args.max_extras:
        failures.append(f"extras {summary['extra_segments']} > {args.max_extras}")
    return failures


def group_by(rows: list[dict[str, Any]], key: str) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        grouped[str(row.get(key) or "unknown")].append(row)
    return grouped


def expected_sort_key(segment: ExpectedSegment) -> tuple:
    return (
        segment.dep_time,
        segment.flight_number or "",
        segment.dep_airport,
        segment.arr_airport,
        segment.pnr,
    )


def expected_dep_date(segment: ExpectedSegment) -> str:
    return segment.dep_time[:10]


def parsed_dep_date(segment: ParsedSegment) -> str:
    return (segment.dep_time or "")[:10]


def _normal_code(value: Any) -> str | None:
    text = "".join(str(value or "").upper().split())
    return text or None


def _normal_flight_number(value: Any) -> str | None:
    text = _normal_code(value)
    if not text:
        return None
    return text.replace(" ", "")


def _normal_timestamp(value: Any) -> str:
    return str(value or "").replace("T", " ")[:19]


def _safe_inline(value: str | None) -> str:
    text = " ".join(str(value or "").replace("`", "'").split())[:140]
    return text.encode("ascii", errors="ignore").decode("ascii")


if __name__ == "__main__":
    main()
