// Tiny local-only CommonJS bundler for the offline passport canvas. React Native
// never evaluates DOM modules; it receives the resulting script as a string.
const fs = require('node:fs'), path = require('node:path'), ts = require('typescript');
const root = path.resolve(__dirname, '../src/components/world-window/passport');
const modules = new Map();
function bundle(file) {
  const id = path.relative(root, file).replaceAll('\\', '/'); if (modules.has(id)) return id;
  modules.set(id, '');
  const source = fs.readFileSync(file, 'utf8');
  const compiled = ts.transpileModule(source, { fileName: file, compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText;
  const output = compiled.replace(/require\("([^\"]+)"\)/g, (_, request) => {
    if (!request.startsWith('.')) throw new Error('Passport must be offline/self-contained: ' + request);
    const base = path.resolve(path.dirname(file), request), resolved = [base, base + '.ts', base + '.js'].find(candidate => fs.existsSync(candidate) && fs.statSync(candidate).isFile());
    if (!resolved) throw new Error('Missing module: ' + request);
    return `require(${JSON.stringify(bundle(resolved))})`;
  }); modules.set(id, output); return id;
}
const entry = bundle(path.join(root, 'passport-runtime.ts'));
const runtime = '(function(){const modules={' + [...modules].map(([id, content]) => `${JSON.stringify(id)}:function(module,exports,require){\n${content}\n}`).join(',\n') + '};const cache={};function require(id){if(cache[id])return cache[id].exports;const module=cache[id]={exports:{}};modules[id](module,module.exports,require);return module.exports;}require(' + JSON.stringify(entry) + ');})();';
const result = '// Generated by node scripts/buildPassportRuntime.js. Includes MIT-licensed StPageFlip geometry; see page-fold/LICENSE.\nexport const passportRuntime = ' + JSON.stringify(runtime) + ';\n';
const target = path.join(root, 'passport-runtime.generated.ts');
if (process.argv.includes('--check')) { if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== result) throw new Error('Passport runtime bundle is stale; run node scripts/buildPassportRuntime.js'); console.log('Passport runtime bundle is current.'); }
else { fs.writeFileSync(target, result); console.log(`Bundled offline passport: ${modules.size} modules, ${Math.round(runtime.length / 1024)} KB`); }
