// Deterministic country IDs, never interpolated labels. No traveler data or network.
const fs = require("node:fs");
const path = require("node:path");
const sharp = require("sharp");
const root = path.resolve(__dirname, "..");
const world = JSON.parse(
  fs.readFileSync(path.join(root, "src/data/worldCountries.json"), "utf8"),
);
const output = path.join(root, "assets/world-window");
const columns = 12,
  rows = 6,
  tileSize = 1024,
  gutter = 1;
function countrySVG(
  width,
  height,
  box = `0 0 ${width} ${height}`,
  size = [width, height],
) {
  const ring = (points) =>
    points
      .map(
        ([lon, lat], i) =>
          `${i ? "L" : "M"}${(((lon + 180) / 360) * width).toFixed(4)},${(((90 - lat) / 180) * height).toFixed(4)}`,
      )
      .join("") + "Z";
  const paths = world.features
    .map((feature, index) => {
      const polygons =
        feature.geometry.type === "Polygon"
          ? [feature.geometry.coordinates]
          : feature.geometry.coordinates;
      return `<path fill="rgb(${index + 1},0,255)" fill-rule="evenodd" d="${polygons.map((polygon) => polygon.map(ring).join("")).join("")}"/>`;
    })
    .join("");
  return Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size[0]}" height="${size[1]}" viewBox="${box}" shape-rendering="crispEdges"><rect x="-2" y="-2" width="${width + 4}" height="${height + 4}" fill="black"/>${[-width, 0, width].map((x) => `<g transform="translate(${x},0)">${paths}</g>`).join("")}</svg>`,
  );
}
async function run() {
  fs.mkdirSync(path.join(output, "country-detail"), { recursive: true });
  for (const width of [2048, 4096])
    await sharp(countrySVG(width, width / 2))
      .png()
      .toFile(
        path.join(
          output,
          width === 2048 ? "country-index.png" : "country-index-4096.png",
        ),
      );
  // Rasterize once, then copy identical neighbor pixels into every gutter.
  // Independent SVG clipping can otherwise disagree at the international date line.
  const masterWidth = columns * tileSize,
    masterHeight = rows * tileSize;
  const master = await sharp(countrySVG(masterWidth, masterHeight))
    .ensureAlpha()
    .raw()
    .toBuffer();
  const manifest = [];
  for (let row = 0; row < rows; row++) {
    const files = [];
    for (let col = 0; col < columns; col++) {
      const name = `country-r${row}-c${col}.png`;
      const side = tileSize + 2 * gutter,
        pixels = Buffer.alloc(side * side * 4);
      for (let y = 0; y < side; y++) {
        const sourceY = Math.max(
          0,
          Math.min(masterHeight - 1, row * tileSize + y - gutter),
        );
        let sourceX = (col * tileSize - gutter + masterWidth) % masterWidth,
          remaining = side,
          dest = y * side * 4;
        while (remaining) {
          const length = Math.min(remaining, masterWidth - sourceX);
          master.copy(
            pixels,
            dest,
            (sourceY * masterWidth + sourceX) * 4,
            (sourceY * masterWidth + sourceX + length) * 4,
          );
          remaining -= length;
          dest += length * 4;
          sourceX = 0;
        }
      }
      await sharp(pixels, { raw: { width: side, height: side, channels: 4 } })
        .png()
        .toFile(path.join(output, "country-detail", name));
      files.push(
        `    require('../../assets/world-window/country-detail/${name}')`,
      );
    }
    manifest.push("  [\n" + files.join(",\n") + "\n  ]");
  }
  fs.writeFileSync(
    path.join(root, "src/data/globeCountryDetailTiles.ts"),
    "// Generated by buildWorldWindowGlobe.cjs. Exact country IDs with one-pixel gutters.\nexport const globeCountryDetailTiles = [\n" +
      manifest.join(",\n") +
      "\n];\n",
  );
  // The old base and high-resolution tiles used different NASA generations.
  // Derive matching bases from the existing 21,600px master; no upscaling.
  for (const width of [2048, 4096])
    await sharp(path.join(root, "assets/globe/blue-marble-day-21600.jpg"))
      .resize(width, width / 2)
      .jpeg({ quality: 91, chromaSubsampling: "4:4:4" })
      .toFile(path.join(output, `nasa-day-base-${width}.jpg`));
  await buildNightAssets();
  console.log(
    `Prepared ${world.features.length} countries, 4096px base and ${rows * columns} 1026px detail tiles (12,288px equivalent); matching NASA bases.`,
  );
}
async function buildNightAssets() {
  const source = path.join(root, "assets/globe/black-marble-2016-13500.jpg");
  const nightSize = 1125,
    width = columns * nightSize,
    height = rows * nightSize;
  const directory = path.join(output, "night-detail");
  fs.mkdirSync(directory, { recursive: true });
  const metadata = await sharp(source).metadata();
  if (metadata.width !== width || metadata.height !== height)
    throw new Error(
      "Night imagery must be the real 13500x6750 NASA master, never upscaled",
    );
  for (const baseWidth of [2048, 4096])
    await sharp(source)
      .resize(baseWidth, baseWidth / 2)
      .jpeg({ quality: 95, chromaSubsampling: "4:4:4" })
      .toFile(path.join(output, `nasa-night-${baseWidth}.jpg`));
  const master = await sharp(source).removeAlpha().raw().toBuffer();
  const manifest = [];
  for (let row = 0; row < rows; row++) {
    const files = [];
    for (let col = 0; col < columns; col++) {
      const side = nightSize + 2 * gutter,
        pixels = Buffer.alloc(side * side * 3);
      for (let y = 0; y < side; y++) {
        const sy = Math.max(
          0,
          Math.min(height - 1, row * nightSize + y - gutter),
        );
        let sx = (col * nightSize - gutter + width) % width,
          remaining = side,
          dest = y * side * 3;
        while (remaining) {
          const length = Math.min(remaining, width - sx);
          master.copy(
            pixels,
            dest,
            (sy * width + sx) * 3,
            (sy * width + sx + length) * 3,
          );
          remaining -= length;
          dest += length * 3;
          sx = 0;
        }
      }
      const name = `night-r${row}-c${col}.jpg`;
      await sharp(pixels, { raw: { width: side, height: side, channels: 3 } })
        .jpeg({ quality: 95, chromaSubsampling: "4:4:4" })
        .toFile(path.join(directory, name));
      files.push(
        `    require('../../assets/world-window/night-detail/${name}')`,
      );
    }
    manifest.push("  [\n" + files.join(",\n") + "\n  ]");
  }
  fs.writeFileSync(
    path.join(root, "src/data/globeNightDetailTiles.ts"),
    "// Generated by buildWorldWindowGlobe.cjs. NASA 2016 night imagery with one-pixel gutters.\nexport const globeNightDetailTiles = [\n" +
      manifest.join(",\n") +
      "\n];\n",
  );
  console.log(
    "Prepared 4096/2048px NASA night bases and 72 bounded 1127px detail tiles.",
  );
}
(process.argv.includes("--night-only") ? buildNightAssets() : run()).catch(
  (error) => {
    console.error(error);
    process.exitCode = 1;
  },
);
