// The cover title is part of the passport artwork. Outline its bundled font so
// Android native SVG and the WebView use identical glyphs before fonts load.
const fs = require('node:fs'), path = require('node:path'), crypto = require('node:crypto');
const { pathToFileURL } = require('node:url');
(async () => {
  const root = path.resolve(__dirname, '..');
  const { default: opentype } = await import(pathToFileURL(path.join(root, 'node_modules/three/examples/jsm/libs/opentype.module.js')));
  const bytes = fs.readFileSync(path.join(root, 'assets/world-window/fonts/Newsreader-Regular.ttf'));
  const font = opentype.parse(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength));
  const options = { kerning: true, letterSpacing: 0.02 }, fontSize = 26;
  const outline = font.getPath('Passport', 0, 0, fontSize, options);
  const value = { path: outline.toPathData(3), advance: font.getAdvanceWidth('Passport', fontSize, options), bounds: outline.getBoundingBox() };
  const source = '// Generated by scripts/buildPassportCover.cjs from bundled Newsreader-Regular.ttf.\n' +
    '// Font SHA256: ' + crypto.createHash('sha256').update(bytes).digest('hex') + '\n' +
    'export const passportCoverLettering = ' + JSON.stringify(value) + ';\n';
  const target = path.join(root, 'src/components/world-window/passport/passport-cover-lettering.generated.ts');
  if (process.argv.includes('--check')) {
    if (fs.readFileSync(target, 'utf8') !== source) throw new Error('Passport cover lettering is stale.');
  } else fs.writeFileSync(target, source);
  console.log('Passport cover lettering ' + (process.argv.includes('--check') ? 'verified.' : 'generated.'));
})().catch(error => { console.error(error); process.exitCode = 1; });
