const { chromium } = require('C:/Users/natha/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),ts=require('typescript'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.resolve(root,'../artifacts/world-window-fidelity'),cache=new Map();
function load(file){if(cache.has(file))return cache.get(file).exports;const module={exports:{}};cache.set(file,module);const output=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText;new Function('module','exports','require',output)(module,module.exports,request=>{if(!request.startsWith('.'))return require(request);let base=path.resolve(path.dirname(file),request);if(base.endsWith('.png')||base.endsWith('.ttf'))return base;if(base.endsWith('.json'))return JSON.parse(fs.readFileSync(base,'utf8'));return load([base,base+'.ts',base+'.tsx',base+'.js'].find(p=>fs.existsSync(p)&&fs.statSync(p).isFile()))});return module.exports;}
const component=f=>load(path.join(root,'src/components/world-window/passport',f)),uri=(file,mime)=>`data:${mime};base64,${fs.readFileSync(file).toString('base64')}`;
const {stampIdentity}=load(path.join(root,'src/components/trotter/stamps/stampIdentity.ts')),{countryIconAssets,stampShapeAssets}=load(path.join(root,'src/assets/generated/stampAssetManifest.ts'));
const {nativeStampTemplate}=component('passport-native-template.ts'),{passportDocument}=component('passport-document.ts');
const shapes={archedCountryCanonical:'arched_country_canonical',archedCountryBanner:'arched_country_banner',archedCountryVariant:'arched_country_variant',circularCityClean:'circular_city_clean',circularCityDoubleLine:'circular_city_double_line',roundedImmigrationCanonical:'rounded_immigration_canonical',roundedImmigrationWithBand:'rounded_immigration_with_band',shieldBadgeRounded:'shield_badge_rounded'};
const countries=[['JP','Japan','NRT'],['SG','Singapore','SIN'],['TW','Taiwan','TPE'],['PH','Philippines','MNL'],['DO','Dominican Republic','PUJ'],['MX','Mexico','MEX'],['NI','Nicaragua','MGA'],['ET','Ethiopia','ADD'],['SL','Somaliland','HGA'],['AE','United Arab Emirates','DXB'],['NL','Netherlands','AMS'],['TN','Tunisia','TUN'],['DE','Germany','FRA'],['GB','United Kingdom','LHR'],['FR','France','CDG'],['US','United States','IAH'],['CA','Canada','YYZ']];
const payload={name:'Traveler',airportLabel:'Most used airport',homeAirport:'IAH',homeAirportName:'Houston',homeAirportCountry:'United States',firstFlightDate:'2016-01-01',flights:145,miles:283884,countries:17,years:[{year:2016,flights:4},{year:2017,flights:2},{year:2018,flights:12},{year:2019,flights:20},{year:2020,flights:14},{year:2021,flights:12},{year:2022,flights:27},{year:2023,flights:12},{year:2024,flights:15},{year:2025,flights:31}],fonts:{},stamps:[]};
payload.register=[{label:'First recorded flight',value:'2016-01-01'},{label:'Most used airport',value:'IAH'},{label:'Most common route',value:'IAH → DFW'},{label:'Furthest flight',value:'DFW → SIN'},{label:'Airports / airlines',value:'57 / 18'}];
for(const [name,file]of Object.entries({Newsreader:'Newsreader-Regular',DMSans:'DMSans-Regular',DMSansBold:'DMSans-Bold',PlexMono:'IBMPlexMono-Medium'}))payload.fonts[name]=uri(path.join(root,'assets/world-window/fonts',file+'.ttf'),'font/ttf');
for(const [code,country,airport]of countries){const identity=stampIdentity(country,code),prefix=country.toLowerCase().replace(/[^a-z0-9]+/g,'_');const art=country==='Nicaragua'?'costa_rica_arenal_volcano':country==='Somaliland'?Object.keys(countryIconAssets).find(k=>k.startsWith('somaliland_')):Object.keys(countryIconAssets).find(k=>k.startsWith(prefix+'_'));payload.stamps.push({code,country:country.toUpperCase(),airport,date:'2025-01-17',color:identity.color,frame:uri(stampShapeAssets[shapes[identity.shape]],'image/png'),icon:art?uri(countryIconAssets[art],'image/png'):country==='Tunisia'?uri(path.join(root,'assets/world-window/passport/tunisia_el_jem.png'),'image/png'):undefined,template:nativeStampTemplate(identity.shape,country.toUpperCase())})}
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});const report=[];for(const width of [320,410]){const page=await browser.newPage({viewport:{width,height:750},deviceScaleFactor:2,reducedMotion:'reduce'});const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>{requests.push(route.request().url());route.abort()});const html=passportDocument(payload).replace('<body>','<body><script>window.__messages=[];window.ReactNativeWebView={postMessage:s=>window.__messages.push(JSON.parse(s))};</script>');await page.setContent(html);await page.waitForFunction(()=>window.__messages.some(m=>m.type==='ready'));const target=page.locator('#book');await target.screenshot({path:path.join(out,`native-passport-${width}-closed.png`)});await page.mouse.click(width*.55,130);await page.waitForFunction(()=>document.querySelector('#status').textContent!=='Passport closed');await target.screenshot({path:path.join(out,`native-passport-${width}-open.png`)});await page.locator('#book').focus();await page.keyboard.press('ArrowRight');await page.waitForTimeout(100);await target.screenshot({path:path.join(out,`native-passport-${width}-stamps.png`)});for(let i=0;i<10;i++)await page.keyboard.press('ArrowRight');await target.screenshot({path:path.join(out,'native-passport-'+width+'-register.png')});for(let i=0;i<10;i++)await page.keyboard.press('ArrowLeft');await page.waitForTimeout(100);assert.equal(await page.locator('#status').textContent(),'Passport closed');assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);report.push({width,status:'closed/open/stamps/back-close passed',fonts:await page.evaluate(()=>Array.from(document.fonts).map(f=>({family:f.family,status:f.status}))),requests,errors});await page.close()}fs.writeFileSync(path.join(out,'native-passport-offline-proof.json'),JSON.stringify(report,null,2));await browser.close();console.log('Offline passport proof passed at 320 and 410: fonts, artwork, open/turn/close, zero network.');})();
