const fs = require('node:fs/promises');
const path = require('node:path');

const rootDir = path.resolve(__dirname, '..');
const photosDir = path.join(rootDir, 'assets', 'photos', 'destinations');
const manifestPath = path.join(rootDir, 'src', 'assets', 'generated', 'destinationPhotoManifest.ts');
const supportedExtensions = new Set(['.jpg', '.jpeg', '.png', '.webp']);

function toAssetKey(filename) {
  return path.basename(filename, path.extname(filename))
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

async function main() {
  await fs.mkdir(photosDir, { recursive: true });
  await fs.mkdir(path.dirname(manifestPath), { recursive: true });

  const filenames = (await fs.readdir(photosDir))
    .filter((filename) => supportedExtensions.has(path.extname(filename).toLowerCase()))
    .sort((a, b) => a.localeCompare(b));

  const lines = [
    '/* eslint-disable @typescript-eslint/no-var-requires */',
    '// Generated by scripts/generateDestinationPhotoManifest.js. Do not edit by hand.',
    "import type { ImageSourcePropType } from 'react-native';",
    '',
    'export const destinationPhotoAssets = {',
  ];

  for (const filename of filenames) {
    lines.push(`  ${toAssetKey(filename)}: require('../../../assets/photos/destinations/${filename}'),`);
  }

  lines.push('} as const satisfies Record<string, ImageSourcePropType>;', '');
  lines.push('export type DestinationPhotoAssetKey = keyof typeof destinationPhotoAssets;', '');

  await fs.writeFile(manifestPath, lines.join('\n'), 'utf8');
  console.log(`Destination photo manifest: ${filenames.length} asset(s)`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
