const fs = require('node:fs/promises');
const path = require('node:path');
const sharp = require('sharp');

const rootDir = path.resolve(__dirname, '..');
const inputs = [
  {
    name: 'country-icons',
    sourceDir: path.join(rootDir, 'assets', 'country-icons'),
    outputDir: path.join(rootDir, 'assets', 'processed', 'country-icons'),
    exportName: 'countryIconAssets',
    manifestPathPrefix: '../../../assets/processed/country-icons',
  },
  {
    name: 'stamp-shapes',
    sourceDir: path.join(rootDir, 'assets', 'stamp-shapes'),
    outputDir: path.join(rootDir, 'assets', 'processed', 'stamp-shapes'),
    exportName: 'stampShapeAssets',
    manifestPathPrefix: '../../../assets/processed/stamp-shapes',
  },
];

const manifestPath = path.join(rootDir, 'src', 'assets', 'generated', 'stampAssetManifest.ts');
const hardWhiteThreshold = 245;
const softWhiteStart = 220;

function isPng(filename) {
  return filename.toLowerCase().endsWith('.png');
}

function toAssetKey(filename) {
  const base = path.basename(filename, path.extname(filename))
    .replace(/^\d+[_-]+/, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');

  return /^[a-z_]/.test(base) ? base : `asset_${base}`;
}

async function ensureCleanDir(dir) {
  await fs.rm(dir, { recursive: true, force: true });
  await fs.mkdir(dir, { recursive: true });
}

function softenWhiteToAlpha(buffer) {
  let transparentPixels = 0;
  let softenedPixels = 0;
  let opaquePixels = 0;

  for (let i = 0; i < buffer.length; i += 4) {
    const red = buffer[i];
    const green = buffer[i + 1];
    const blue = buffer[i + 2];
    const sourceAlpha = buffer[i + 3];
    const luma = red * 0.299 + green * 0.587 + blue * 0.114;
    let alpha = sourceAlpha;

    if (red >= hardWhiteThreshold && green >= hardWhiteThreshold && blue >= hardWhiteThreshold) {
      alpha = 0;
      transparentPixels += 1;
    } else if (luma > softWhiteStart) {
      const fade = (hardWhiteThreshold - luma) / (hardWhiteThreshold - softWhiteStart);
      alpha = Math.max(0, Math.min(sourceAlpha, Math.round(255 * fade)));
      softenedPixels += 1;
    } else {
      alpha = sourceAlpha;
      opaquePixels += 1;
    }

    buffer[i] = 0;
    buffer[i + 1] = 0;
    buffer[i + 2] = 0;
    buffer[i + 3] = alpha;
  }

  return { transparentPixels, softenedPixels, opaquePixels };
}

async function processPng(inputPath, outputPath) {
  const trimmed = sharp(inputPath)
    .trim({ background: '#ffffff', threshold: 12 })
    .ensureAlpha();

  const { data, info } = await trimmed.raw().toBuffer({ resolveWithObject: true });
  const stats = softenWhiteToAlpha(data);

  await sharp(data, {
    raw: {
      width: info.width,
      height: info.height,
      channels: 4,
    },
  })
    .png({ compressionLevel: 9 })
    .toFile(outputPath);

  return { width: info.width, height: info.height, ...stats };
}

async function processGroup(group) {
  await ensureCleanDir(group.outputDir);
  const filenames = (await fs.readdir(group.sourceDir)).filter(isPng).sort((a, b) => a.localeCompare(b));
  const entries = [];

  for (const filename of filenames) {
    const inputPath = path.join(group.sourceDir, filename);
    const outputFilename = `${path.basename(filename, path.extname(filename))}.png`;
    const outputPath = path.join(group.outputDir, outputFilename);
    const key = toAssetKey(filename);
    const stats = await processPng(inputPath, outputPath);

    entries.push({
      key,
      filename: outputFilename,
      requirePath: `${group.manifestPathPrefix}/${outputFilename}`.replaceAll('\\', '/'),
      ...stats,
    });
  }

  return { ...group, entries };
}

function renderManifest(groups) {
  const lines = [
    '/* eslint-disable @typescript-eslint/no-var-requires */',
    '// Generated by scripts/prepareStampAssets.js. Do not edit by hand.',
    '',
  ];

  for (const group of groups) {
    lines.push(`export const ${group.exportName} = {`);
    for (const entry of group.entries) {
      lines.push(`  ${entry.key}: require('${entry.requirePath}'),`);
    }
    lines.push('} as const;', '');
  }

  lines.push(`export type CountryIconAssetKey = keyof typeof ${groups[0].exportName};`);
  lines.push(`export type StampShapeAssetKey = keyof typeof ${groups[1].exportName};`);
  lines.push('');

  return lines.join('\n');
}

async function main() {
  const groups = [];
  for (const group of inputs) {
    groups.push(await processGroup(group));
  }

  await fs.mkdir(path.dirname(manifestPath), { recursive: true });
  await fs.writeFile(manifestPath, renderManifest(groups), 'utf8');

  for (const group of groups) {
    const pixels = group.entries.reduce(
      (total, entry) => ({
        transparent: total.transparent + entry.transparentPixels,
        softened: total.softened + entry.softenedPixels,
        opaque: total.opaque + entry.opaquePixels,
      }),
      { transparent: 0, softened: 0, opaque: 0 },
    );

    console.log(
      `${group.name}: processed ${group.entries.length} PNGs, ` +
      `${pixels.transparent.toLocaleString()} transparent px, ` +
      `${pixels.softened.toLocaleString()} softened edge px, ` +
      `${pixels.opaque.toLocaleString()} opaque px`,
    );
  }
  console.log(`Manifest written to ${path.relative(rootDir, manifestPath)}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
