// Explicit curated refresh; never scrapes the whole catalogue or user data.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const sharp = require('sharp');
const codes = '3U 5J 6E 7C 8M A3 AC AF AI AK AS AY AZ BA BI CA CI CM CX D7 EI EY FI FZ G9 GA GF HA HO HU HX HY I2 J2 JD JL JQ KC KE KL KQ KU LA LH LO LX MH MS MU NZ OD OS OU OZ PC PR QF QR RJ RO SA SK SN SQ SU SV TG TK TP TR U2 VA VN VS VY WS WY XQ'.split(' ');
const directory = path.resolve(__dirname, '../assets/world-window/airlines');
const sourceBase = 'https://assets.duffel.com/img/airlines/for-light-background/full-color-logo/';
const sha = value => crypto.createHash('sha256').update(value).digest('hex');

async function main() {
  const entries = [], unavailable = [];
  // Four concurrent public assets; only symbols, never wide lockups or invented marks.
  for (let index = 0; index < codes.length; index += 4) {
    await Promise.all(codes.slice(index, index + 4).map(async code => {
      const url = `${sourceBase}${code}.svg`;
      try {
        const response = await fetch(url, { headers: { 'User-Agent': 'Trotter-asset-audit/1.0' }, signal: AbortSignal.timeout(12000) });
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const source = Buffer.from(await response.arrayBuffer());
        if (!source.toString('utf8').includes('<svg') || source.length > 200000) throw new Error('Invalid SVG');
        const png = await sharp(source, { density: 144 }).resize(128, 128, { fit: 'contain', background: '#00000000' }).png().toBuffer();
        fs.writeFileSync(path.join(directory, `${code}.png`), png);
        entries.push({ code, sourceUrl: url, sourceSha256: sha(source), sha256: sha(png), width: 128, height: 128, bytes: png.length });
      } catch (error) { unavailable.push({ code, reason: error.message }); }
    }));
  }
  entries.sort((a, b) => a.code.localeCompare(b.code));
  const manifest = { version: 1, retrievedAt: new Date().toISOString(), provider: 'Duffel airline symbol CDN', documentation: 'https://duffel.com/docs/api/airlines', rights: 'Airline trademarks belong to their respective owners. Assets identify carriers; no ownership or endorsement is claimed.', entries, unavailable };
  fs.writeFileSync(path.join(directory, 'sources.json'), JSON.stringify(manifest, null, 2) + '\n');
  const all = fs.readdirSync(directory).filter(name => /^[A-Z0-9]{2}\.png$/.test(name)).sort();
  fs.writeFileSync(path.resolve(__dirname, '../src/components/world-window/airlineLogoAssets.ts'), `// Generated by scripts/updateAirlineLogos.cjs. Existing approved marks are preserved.\nimport type { ImageSourcePropType } from 'react-native';\nexport const bundledAirlineLogos: Readonly<Record<string, ImageSourcePropType>> = {\n${all.map(name => `  '${name.slice(0, 2)}': require('../../../assets/world-window/airlines/${name}'),`).join('\n')}\n};\n`);
  console.log(JSON.stringify({ bundled: all.length, newlyVerified: entries.length, unavailable, addedBytes: entries.reduce((sum, entry) => sum + entry.bytes, 0) }));
}
main().catch(error => { console.error(error.message); process.exitCode = 1; });
